// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyyglcyjoolykgcigtma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5eWdsY3lqb29seWtnY2lndG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTM4MzMsImV4cCI6MjA1NjU4OTgzM30.eWDe_aE0CKiinoc5kt9Qj92jK4zMbimDwrl2BeMG3ZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);